/**
 * Vedic Technical Summary & Evidence Layer — Phase 4F.
 *
 * THIS IS AN AGGREGATION / NORMALIZATION LAYER ONLY. It performs ZERO new
 * astronomical calculation, ZERO new sidereal/Bhava/Nakshatra/dignity
 * computation, and creates NO new Jyotish doctrine. Every field below is
 * read (and, where noted, regrouped/relabeled for traceability) from an
 * already-computed, already-locked upstream result: Phase 4A (sidereal
 * Lagna/Navagraha position), Phase 4B (Whole-Sign Bhava structure and
 * house ownership), Phase 4C (Nakshatra/Pada), Phase 4D (dignity and
 * technical condition), and Phase 4E (dispositor chains, loops, and
 * lordship structure).
 *
 * Phase 4A-4E calculate technical evidence. Phase 4F organizes that
 * evidence for inspection/export. It does not reinterpret it:
 *
 *   - NO Vimshottari Dasha, Navamsa/Varga, Shadbala, Ashtakavarga,
 *     Drishti, or Yoga detection of any kind.
 *   - NO functional benefic/malefic, Yogakaraka, Maraka, or Badhaka.
 *   - NO temporary/compound friendship, no Avastha.
 *   - NO score of any kind (grahaScore, bhavaScore, strengthScore, ...).
 *   - NO interpretive label ("strong", "weak", "auspicious",
 *     "inauspicious", career/relationship/wealth semantics, or any
 *     narrative text).
 *
 * REUSE, NEVER REBUILD: this module takes the already-built `grahas`
 * (Phase 4A), `bhava` (Phase 4B), `nakshatra` (Phase 4C), `condition`
 * (Phase 4D), and `lordship` (Phase 4E) objects, plus the assembled
 * `chart.vedic.meta`, as read-only input. It never mutates any of them,
 * and the value it returns is deep-cloned (`structuredClone`) before
 * being handed back, so mutating `chart.vedic.summary` afterward can
 * never corrupt any locked Phase 4A-4E source structure.
 *
 * RAHU/KETU: only evidence actually supported by Phase 4A-4E is
 * included. Dignity, house ownership, and multi-step dispositor chains
 * are never fabricated for the lunar nodes — those sections carry an
 * explicit `applicable: false` rather than an invented value, mirroring
 * exactly how Phase 4D/4E already treat the nodes.
 *
 * DISPOSITOR LOOP ORDERED PATH (Part I): Phase 4E's public output
 * canonicalizes a loop's membership by alphabetically sorting display
 * names for deduplication (`lordship.js`'s `canonicalizeLoop`) — the
 * actual DIRECTIONAL cycle order that produced that loop is not
 * preserved in Phase 4E's returned structure. Rather than reconstructing
 * or inferring that order here (which would mean this aggregation layer
 * quietly re-deriving a fact Phase 4E itself does not expose), this
 * module preserves the canonical membership set verbatim
 * (`canonicalMembers`) and explicitly reports `orderedPath: null`,
 * recorded as its own `"not_implemented"` marker
 * (`DISPOSITOR_LOOP_ORDERED_PATH_STATUS`) so it surfaces automatically
 * in `unresolvedConventions` rather than being silently absent.
 *
 * UNRESOLVED CONVENTIONS (Part L): generated by scanning the LIVE
 * `chart.vedic.meta` values (plus this module's own
 * `DISPOSITOR_LOOP_ORDERED_PATH_STATUS`) through an explicit, documented
 * classifier (`classifyImplementationStatus`) — never a hard-coded topic
 * list, and never a broad substring match on a word like `"not"` (several
 * INTENTIONAL, permanent policy outcomes also happen to contain "not" —
 * see below). A topic disappears from this list on its own the moment a
 * future phase resolves it (i.e. its meta value stops classifying as
 * `"unresolved"`).
 *
 * PRE-LOCK AUDIT (see README §24.1 for the full trail): the original
 * detector recognized exactly three literal strings
 * (`"not_implemented"`/`"not_yet_implemented"`/`"deferred"`) via a plain
 * `Set.has()` equality check. Auditing the complete live
 * `chart.vedic.meta` inventory against the three explicit categories
 * below confirmed the equality check had zero false positives and zero
 * false negatives for TODAY's metadata (every genuinely-deferred field in
 * this project has always used the single literal `"not_implemented"`),
 * but the policy itself was under-specified: it had no documented,
 * deterministic answer for a future value shaped like
 * `"not_implemented_pending_research"` or `"deferred_due_to_..."`
 * (Phase 3H's own classical marker vocabulary already uses that second
 * shape), and it relied on an unexplained implicit exclusion of `"none"`
 * rather than a named category. `classifyImplementationStatus` below
 * replaces the bare equality check with three explicit, named outcomes:
 *
 *   - `"unresolved"`: a genuinely deferred/unbuilt technical feature a
 *     future phase could implement. Recognized: the exact literal this
 *     project has used everywhere since Phase 4B (`"not_implemented"`),
 *     the generic forms the Phase 4F brief itself named
 *     (`"not_yet_implemented"`, `"not_yet_evaluated"` — the latter
 *     already established Phase 3H vocabulary, reused here for
 *     cross-project consistency — and exact `"deferred"`), and two
 *     PREFIXES (`"not_implemented_"`, `"deferred_"`) so a more specific
 *     future value in either family is still recognized without a bare
 *     substring match on "not".
 *   - `"intentional_not_applicable"`: a PERMANENT, deliberate policy
 *     outcome that happens to contain "not" but is never a deferred
 *     feature — `"none"` (this project's own explicit "we do not
 *     interpret, ever" marker, e.g. `vedicInterpretation: "none"`),
 *     `"not_applicable"`, and `"not_assigned_due_to_traditional_variance"`
 *     (Rahu/Ketu dignity — individually named, not pattern-matched: this
 *     project's own research, documented in `dignityTables.js`/
 *     `condition.js`, established that own-sign/exaltation/Moolatrikona
 *     are genuinely disputed across Jyotish schools for the lunar nodes,
 *     so this is a permanent selected policy, not "not built yet").
 *   - `"implemented"`: everything else — an actual chosen convention name
 *     (e.g. `"bphs_critical_edition"`) or descriptive fact. This also
 *     covers `externalVerification: "swiss_ephemeris_dev_only_not_production"`
 *     — a note about the DEV-ONLY VERIFICATION TOOLING'S deployment scope,
 *     not a Jyotish feature awaiting implementation, so it is classified
 *     `"implemented"` (a settled, permanent statement) rather than
 *     pattern-matched into `"unresolved"` off the word "not".
 *
 * The audit reran the full live inventory under this explicit policy and
 * confirmed the resulting topic list is IDENTICAL to the prior one (13
 * topics) for the locked verification chart — the refactor changes the
 * classification's explicitness and future robustness, not today's
 * output. See README §24.1 for the complete inventory and reasoning.
 */

import { RASHIS } from "./rashi.js";
import { NAKSHATRAS } from "./nakshatra.js";
import { GRAHA_DISPLAY_NAME, NAVAGRAHA_ORDER } from "./grahaNames.js";
import { CLASSICAL_GRAHA_KEYS } from "./dignityTables.js";

export const TECHNICAL_SUMMARY_VERSION = "phase_4f_v1";
export const TECHNICAL_SUMMARY_TYPE = "normalized_evidence_layer";
export const TECHNICAL_SUMMARY_INTERPRETATION = "none";
export const SOURCE_PHASES = ["phase_4a", "phase_4b", "phase_4c", "phase_4d", "phase_4e"];

/** See module doc comment "DISPOSITOR LOOP ORDERED PATH" - a genuinely new limitation this phase discovers, not silently hidden. */
export const DISPOSITOR_LOOP_ORDERED_PATH_STATUS = "not_implemented";

const NODE_KEYS = ["rahu", "ketu"];

/** Reverse lookup, classical Grahas only (a Bhava/Lagna lord is always one of the seven classical Grahas - never a node). */
const KEY_BY_DISPLAY_NAME = Object.fromEntries(CLASSICAL_GRAHA_KEYS.map((k) => [GRAHA_DISPLAY_NAME[k], k]));

const PROVENANCE = {
  POSITION: "phase_4a",
  BHAVA: "phase_4b",
  NAKSHATRA: "phase_4c",
  DIGNITY_CONDITION: "phase_4d",
  LORDSHIP_DISPOSITOR: "phase_4e",
};

/** Exact-match strings that always mean a genuinely deferred/unbuilt feature - see module doc comment "UNRESOLVED CONVENTIONS" for the full audit trail on each. */
const UNRESOLVED_EXACT_VALUES = new Set(["not_implemented", "not_yet_implemented", "not_yet_evaluated", "deferred"]);
/** Prefixes that also mean "unresolved" for a more specific future value in either family, without a bare substring match on "not". */
const UNRESOLVED_PREFIXES = ["not_implemented_", "deferred_"];
/** Exact-match strings that are a PERMANENT, deliberate policy/architecture outcome - never a deferred feature, even though each happens to contain "not". Individually named, never pattern-matched. */
const INTENTIONAL_NOT_APPLICABLE_EXACT_VALUES = new Set(["none", "not_applicable", "not_assigned_due_to_traditional_variance"]);

/**
 * Classifies one `chart.vedic.meta` (or this module's own) status string
 * into exactly one of three explicit, documented outcomes - see the
 * module doc comment "UNRESOLVED CONVENTIONS" for the full rationale and
 * pre-lock audit. Deterministic and explainable: no broad substring
 * match on words like "not".
 * @param {string} value
 * @returns {"unresolved"|"intentional_not_applicable"|"implemented"}
 */
export function classifyImplementationStatus(value) {
  if (INTENTIONAL_NOT_APPLICABLE_EXACT_VALUES.has(value)) return "intentional_not_applicable";
  if (UNRESOLVED_EXACT_VALUES.has(value)) return "unresolved";
  if (UNRESOLVED_PREFIXES.some((prefix) => value.startsWith(prefix))) return "unresolved";
  return "implemented";
}

/** camelCase meta key -> snake_case topic label, e.g. "functionalBenefic" -> "functional_benefic". Never a hand-curated topic list (Part L). */
function topicFromMetaKey(key) {
  return key.replace(/([A-Z])/g, "_$1").toLowerCase();
}

function scanForUnresolved(obj, source) {
  const found = [];
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === "string" && classifyImplementationStatus(value) === "unresolved") {
      found.push({ topic: topicFromMetaKey(key), metaKey: key, status: value, source });
    }
  }
  return found;
}

function buildUnresolvedConventions(vedicMeta) {
  return [
    ...scanForUnresolved(vedicMeta, "chart.vedic.meta"),
    ...scanForUnresolved(
      { dispositorLoopOrderedPath: DISPOSITOR_LOOP_ORDERED_PATH_STATUS },
      "chart.vedic.summary.lordship.dispositorNetwork",
    ),
  ];
}

function buildChartOverview({ meta, lagna, bhava, nakshatra }) {
  return {
    zodiacType: meta.zodiacType,
    ayanamsha: meta.ayanamsha,
    ayanamshaImplementation: meta.ayanamshaImplementation,
    ayanamshaIncludesNutation: meta.ayanamshaIncludesNutation,
    vedicNodeType: meta.vedicNodeType,
    lagna: {
      siderealLongitude: lagna.siderealLongitude,
      rashi: lagna.rashi,
      degreeInRashi: lagna.degreeWithinRashi,
      nakshatra: nakshatra.lagna.nakshatra,
      pada: nakshatra.lagna.pada,
      nakshatraLord: nakshatra.lagna.nakshatraLord,
      lagnaLord: bhava.lagna.lord,
    },
    bhavaSystem: meta.bhavaSystem,
    houseLordshipSystem: meta.houseLordshipSystem,
    nakshatraSystem: meta.nakshatraSystem,
    vedicDignitySystem: meta.vedicDignitySystem,
    dispositorSystem: meta.dispositorSystem,
    provenance: { ...PROVENANCE },
  };
}

/** Whether `displayName` (e.g. "Mars") is a member of any chart-level dispositor loop (Phase 4E). Classical Grahas only - a node can never appear in a loop (Rahu/Ketu can never be a link in any dispositor chain). */
function isDispositorLoopMember(displayName, loops) {
  return loops.some((loop) => loop.members.includes(displayName));
}

function buildClassicalGrahaEvidence(key, { grahas, bhava, nakshatra, condition, lordship }) {
  const g = grahas[key];
  const placement = bhava.grahaPlacements[key];
  const n = nakshatra.grahas[key];
  const c = condition.planets[key];
  const role = lordship.planetaryLordshipRoles[key];
  const dispositorInfo = lordship.dispositors[key];
  const chainInfo = lordship.dispositorChains[key];
  const displayName = GRAHA_DISPLAY_NAME[key];
  const isLoopMember = isDispositorLoopMember(displayName, lordship.loops);

  const flags = [];
  if (g.motion.retrograde) flags.push("retrograde");
  if (c.condition.combustion.isCombust) flags.push("combust");
  if (c.dignity.isOwnSign) flags.push("own_sign");
  if (c.dignity.isExaltedSign) flags.push("exalted_sign");
  if (c.dignity.isDebilitatedSign) flags.push("debilitated_sign");
  if (c.dignity.isMoolatrikona) flags.push("moolatrikona");
  if (c.dignity.isExactExaltationPoint) flags.push("exact_exaltation_point");
  if (c.dignity.isExactDebilitationPoint) flags.push("exact_debilitation_point");
  if (dispositorInfo.isSelfDispositor) flags.push("self_dispositor");
  if (isLoopMember) flags.push("dispositor_loop_member");

  return {
    identity: { id: key, name: displayName },
    position: {
      tropicalLongitude: g.tropicalLongitude,
      siderealLongitude: g.siderealLongitude,
      rashi: g.rashi,
      degreeInRashi: g.degreeWithinRashi,
      motion: { ...g.motion },
    },
    bhava: { number: placement.bhavaNumber, rashi: placement.rashi },
    nakshatra: { name: n.nakshatra, number: n.nakshatraNumber, lord: n.nakshatraLord, pada: n.pada, degreeWithinNakshatra: n.degreeWithinNakshatra },
    dignity: {
      applicable: true,
      isOwnSign: c.dignity.isOwnSign,
      isExaltedSign: c.dignity.isExaltedSign,
      isDebilitatedSign: c.dignity.isDebilitatedSign,
      isMoolatrikona: c.dignity.isMoolatrikona,
      isExactExaltationPoint: c.dignity.isExactExaltationPoint,
      isExactDebilitationPoint: c.dignity.isExactDebilitationPoint,
      dignityLabels: [...c.dignity.dignityLabels],
      rashiDignityStatus: c.dignity.rashiDignityStatus,
      signLord: c.signRelationship.signLord,
      naturalRelationshipToSignLord: c.signRelationship.naturalRelationshipToSignLord,
    },
    condition: {
      retrograde: c.condition.isRetrograde,
      combustion: {
        applicable: true,
        isCombust: c.condition.combustion.isCombust,
        solarElongationDegrees: c.condition.combustion.solarElongationDegrees,
        thresholdDegrees: c.condition.combustion.thresholdDegrees,
      },
    },
    ownership: {
      applicable: true,
      ownedBhavas: [...role.ownedHouses],
      kendra: [...role.ownedKendraHouses],
      trikona: [...role.ownedTrikonaHouses],
      dusthana: [...role.ownedDusthanaHouses],
      upachaya: [...role.ownedUpachayaHouses],
      ownsKendra: role.ownsKendra,
      ownsTrikona: role.ownsTrikona,
      ownsDusthana: role.ownsDusthana,
      ownsUpachaya: role.ownsUpachaya,
      ownsKendraAndTrikona: role.ownsKendraAndTrikona,
    },
    dispositor: {
      immediate: dispositorInfo.dispositor,
      isSelfDispositor: dispositorInfo.isSelfDispositor,
      chainApplicable: true,
      chain: [...chainInfo.chain],
      finalDispositor: chainInfo.finalDispositor,
      loop: chainInfo.loop ? { type: chainInfo.loop.type, members: [...chainInfo.loop.members] } : null,
    },
    flags,
    provenance: {
      position: PROVENANCE.POSITION,
      bhava: PROVENANCE.BHAVA,
      nakshatra: PROVENANCE.NAKSHATRA,
      dignity: PROVENANCE.DIGNITY_CONDITION,
      condition: PROVENANCE.DIGNITY_CONDITION,
      ownership: PROVENANCE.LORDSHIP_DISPOSITOR,
      dispositor: PROVENANCE.LORDSHIP_DISPOSITOR,
    },
  };
}

function buildNodeGrahaEvidence(key, { grahas, bhava, nakshatra, condition, lordship }) {
  const g = grahas[key];
  const placement = bhava.grahaPlacements[key];
  const n = nakshatra.grahas[key];
  const nodeCondition = condition.nodes[key];
  const dispositorInfo = lordship.dispositors[key];
  const displayName = GRAHA_DISPLAY_NAME[key];

  const flags = [];
  if (g.motion.retrograde) flags.push("retrograde");

  return {
    identity: { id: key, name: displayName },
    position: {
      tropicalLongitude: g.tropicalLongitude,
      siderealLongitude: g.siderealLongitude,
      rashi: g.rashi,
      degreeInRashi: g.degreeWithinRashi,
      motion: { ...g.motion },
      nodeType: g.nodeType,
    },
    bhava: { number: placement.bhavaNumber, rashi: placement.rashi },
    nakshatra: { name: n.nakshatra, number: n.nakshatraNumber, lord: n.nakshatraLord, pada: n.pada, degreeWithinNakshatra: n.degreeWithinNakshatra },
    dignity: { applicable: false, convention: nodeCondition.dignityConvention },
    condition: {
      retrograde: nodeCondition.isRetrograde,
      combustion: { applicable: false },
    },
    ownership: { applicable: false },
    dispositor: {
      immediate: dispositorInfo.dispositor,
      isSelfDispositor: dispositorInfo.isSelfDispositor,
      chainApplicable: false,
      chain: null,
      finalDispositor: null,
      loop: null,
    },
    flags,
    provenance: {
      position: PROVENANCE.POSITION,
      bhava: PROVENANCE.BHAVA,
      nakshatra: PROVENANCE.NAKSHATRA,
      dignity: PROVENANCE.DIGNITY_CONDITION,
      condition: PROVENANCE.DIGNITY_CONDITION,
      ownership: PROVENANCE.LORDSHIP_DISPOSITOR,
      dispositor: PROVENANCE.LORDSHIP_DISPOSITOR,
    },
  };
}

function buildGrahaEvidenceMap(sources) {
  const grahasEvidence = {};
  for (const key of CLASSICAL_GRAHA_KEYS) {
    grahasEvidence[key] = buildClassicalGrahaEvidence(key, sources);
  }
  for (const key of NODE_KEYS) {
    grahasEvidence[key] = buildNodeGrahaEvidence(key, sources);
  }
  return grahasEvidence;
}

/** 12 normalized Bhava evidence records (Part F), built primarily from Phase 4E's own `houseLordMatrix` (which already combines Phase 4B's placement facts with Phase 4D's dignity/retrograde/combustion evidence for that Bhava's lord) plus Phase 4B's own `houses` for occupant Grahas and Phase 4E's own `houseGroups` for membership. */
function buildBhavaEvidence({ bhava, condition, lordship }) {
  return lordship.houseLordMatrix.map((row) => {
    const house = bhava.houses[row.sourceBhava - 1];
    const lordKey = KEY_BY_DISPLAY_NAME[row.lord];
    return {
      bhavaNumber: row.sourceBhava,
      rashi: row.sourceRashi,
      lord: row.lord,
      grahas: [...house.grahas],
      lordPlacement: { lordRashi: row.lordRashi, lordBhava: row.lordBhava },
      lordCondition: {
        dignityLabels: [...condition.planets[lordKey].dignity.dignityLabels],
        rashiDignityStatus: row.lordDignityStatus,
        retrograde: row.lordIsRetrograde,
        combustion: row.lordIsCombust,
      },
      houseGroups: {
        isKendra: lordship.houseGroups.kendra.includes(row.sourceBhava),
        isTrikona: lordship.houseGroups.trikona.includes(row.sourceBhava),
        isDusthana: lordship.houseGroups.dusthana.includes(row.sourceBhava),
        isUpachaya: lordship.houseGroups.upachaya.includes(row.sourceBhava),
      },
      provenance: { rashiAndLord: PROVENANCE.BHAVA, lordCondition: PROVENANCE.DIGNITY_CONDITION, houseGroups: PROVENANCE.LORDSHIP_DISPOSITOR },
    };
  });
}

/** Normalized Lagna Lord evidence (Part G), extending Phase 4E's own `lagnaLordNetwork` with the lord's Phase 4D dignity and Phase 4C Nakshatra - no interpretation of that condition. */
function buildLagnaLordEvidence({ nakshatra, condition, lordship }) {
  const net = lordship.lagnaLordNetwork;
  const lordKey = KEY_BY_DISPLAY_NAME[net.lagnaLord];
  const lordCondition = condition.planets[lordKey];
  const lordNakshatra = nakshatra.grahas[lordKey];

  return {
    lagnaRashi: net.lagnaRashi,
    lagnaLord: net.lagnaLord,
    lagnaLordRashi: net.lagnaLordRashi,
    lagnaLordBhava: net.lagnaLordBhava,
    lagnaLordDignity: {
      dignityLabels: [...lordCondition.dignity.dignityLabels],
      rashiDignityStatus: lordCondition.dignity.rashiDignityStatus,
    },
    lagnaLordNakshatra: { name: lordNakshatra.nakshatra, lord: lordNakshatra.nakshatraLord, pada: lordNakshatra.pada },
    lagnaLordDispositor: net.lagnaLordDispositor,
    dispositorChain: [...net.dispositorChain],
    finalDispositor: net.finalDispositor,
    loop: net.loop ? { type: net.loop.type, members: [...net.loop.members] } : null,
    provenance: {
      lagnaAndLord: PROVENANCE.BHAVA,
      dignity: PROVENANCE.DIGNITY_CONDITION,
      nakshatra: PROVENANCE.NAKSHATRA,
      dispositor: PROVENANCE.LORDSHIP_DISPOSITOR,
    },
  };
}

/** Normalized planetary lordship evidence (Part H) for the seven classical Grahas - never derives functional benefic/malefic, Yogakaraka, Maraka, or Badhaka. */
function buildLordshipPlanetsEvidence({ grahas, bhava, condition, lordship }) {
  const planets = {};
  for (const key of CLASSICAL_GRAHA_KEYS) {
    const role = lordship.planetaryLordshipRoles[key];
    const c = condition.planets[key];
    planets[key] = {
      planet: GRAHA_DISPLAY_NAME[key],
      ownedBhavas: [...role.ownedHouses],
      ownedRashis: role.ownedHouses.map((h) => bhava.houses[h - 1].rashi),
      ownedKendraHouses: [...role.ownedKendraHouses],
      ownedTrikonaHouses: [...role.ownedTrikonaHouses],
      ownedDusthanaHouses: [...role.ownedDusthanaHouses],
      ownedUpachayaHouses: [...role.ownedUpachayaHouses],
      ownsKendra: role.ownsKendra,
      ownsTrikona: role.ownsTrikona,
      ownsDusthana: role.ownsDusthana,
      ownsUpachaya: role.ownsUpachaya,
      ownsKendraAndTrikona: role.ownsKendraAndTrikona,
      currentBhava: bhava.grahaPlacements[key].bhavaNumber,
      currentRashi: grahas[key].rashi,
      dignityLabels: [...c.dignity.dignityLabels],
      retrograde: c.condition.isRetrograde,
      combustion: c.condition.combustion.isCombust,
      dispositor: lordship.dispositors[key].dispositor,
      provenance: { ownershipAndDispositor: PROVENANCE.LORDSHIP_DISPOSITOR, currentPlacement: PROVENANCE.BHAVA, dignityAndCondition: PROVENANCE.DIGNITY_CONDITION },
    };
  }
  return planets;
}

/** Normalized dispositor-network summary (Part I) - see module doc comment for why `orderedPath` is explicitly `null`. */
function buildDispositorNetwork({ lordship }) {
  const immediateDispositors = {};
  for (const key of NAVAGRAHA_ORDER) {
    immediateDispositors[key] = { ...lordship.dispositors[key] };
  }

  const chains = {};
  const finalDispositors = {};
  for (const key of CLASSICAL_GRAHA_KEYS) {
    const info = lordship.dispositorChains[key];
    chains[key] = { chain: [...info.chain], finalDispositor: info.finalDispositor, loop: info.loop ? { type: info.loop.type, members: [...info.loop.members] } : null };
    finalDispositors[key] = info.finalDispositor;
  }

  const loops = lordship.loops.map((loop) => ({
    canonicalMembers: [...loop.members],
    orderedPath: null,
  }));

  return {
    immediateDispositors,
    chains,
    finalDispositors,
    loops,
    orderedPathStatus: DISPOSITOR_LOOP_ORDERED_PATH_STATUS,
    provenance: PROVENANCE.LORDSHIP_DISPOSITOR,
  };
}

/** Factual relationship/index layer (Part J) - grouping only, never a semantic ("careerPlanets") index. */
function buildRelationships({ grahas, bhava, nakshatra }) {
  const grahasByBhava = {};
  for (const house of bhava.houses) {
    grahasByBhava[house.bhavaNumber] = [...house.grahas];
  }

  const grahasByRashi = {};
  for (const r of RASHIS) grahasByRashi[r.name] = [];
  for (const key of NAVAGRAHA_ORDER) grahasByRashi[grahas[key].rashi].push(GRAHA_DISPLAY_NAME[key]);

  const grahasByNakshatra = {};
  for (const nk of NAKSHATRAS) grahasByNakshatra[nk.name] = [];
  for (const key of NAVAGRAHA_ORDER) grahasByNakshatra[nakshatra.grahas[key].nakshatra].push(GRAHA_DISPLAY_NAME[key]);

  const bhavasByLord = {};
  for (const key of CLASSICAL_GRAHA_KEYS) {
    bhavasByLord[GRAHA_DISPLAY_NAME[key]] = [...(bhava.planetaryHouseOwnership[key] ?? [])];
  }

  return {
    grahasByBhava,
    grahasByRashi,
    grahasByNakshatra,
    bhavasByLord,
    provenance: { grahasByBhava: PROVENANCE.BHAVA, grahasByRashi: PROVENANCE.POSITION, grahasByNakshatra: PROVENANCE.NAKSHATRA, bhavasByLord: PROVENANCE.BHAVA },
  };
}

/**
 * Builds the Phase 4F `chart.vedic.summary` structure from already-locked
 * Phase 4A-4E data. Pure aggregation/normalization - no new astronomical
 * calculation, no new astrology rule, no mutation of any input.
 *
 * @param {object} params
 * @param {object} params.meta the assembled `chart.vedic.meta` (Phase 4A-4E fields, read live for `unresolvedConventions`)
 * @param {object} params.lagna Phase 4A `chart.vedic.lagna`
 * @param {object} params.grahas Phase 4A `chart.vedic.grahas`
 * @param {object} params.bhava Phase 4B `chart.vedic.bhava`
 * @param {object} params.nakshatra Phase 4C `chart.vedic.nakshatra`
 * @param {object} params.condition Phase 4D `chart.vedic.condition`
 * @param {object} params.lordship Phase 4E `chart.vedic.lordship`
 * @returns {object} `chart.vedic.summary` (deep-cloned, mutation-isolated from every input)
 */
export function buildVedicTechnicalSummary({ meta, lagna, grahas, bhava, nakshatra, condition, lordship }) {
  const sources = { meta, lagna, grahas, bhava, nakshatra, condition, lordship };

  const summary = {
    meta: {
      technicalSummaryVersion: TECHNICAL_SUMMARY_VERSION,
      technicalSummaryType: TECHNICAL_SUMMARY_TYPE,
      technicalSummaryInterpretation: TECHNICAL_SUMMARY_INTERPRETATION,
      sourcePhases: [...SOURCE_PHASES],
    },
    chartOverview: buildChartOverview(sources),
    grahas: buildGrahaEvidenceMap(sources),
    bhavas: buildBhavaEvidence(sources),
    lagnaLordNetwork: buildLagnaLordEvidence(sources),
    lordship: {
      planets: buildLordshipPlanetsEvidence(sources),
      dispositorNetwork: buildDispositorNetwork(sources),
    },
    relationships: buildRelationships(sources),
    unresolvedConventions: buildUnresolvedConventions(meta),
    provenance: {
      phase_4a: "sidereal_foundation_and_navagraha_position",
      phase_4b: "bhava_house_structure",
      phase_4c: "nakshatra_pada",
      phase_4d: "dignity_and_planetary_condition",
      phase_4e: "dispositor_lordship_functional_structure",
    },
  };

  // Deep-clone before returning (Part S): guarantees mutating
  // `chart.vedic.summary` afterward can never reach back into any
  // locked Phase 4A-4E source structure, without having to manually
  // track every nested array/object reference above.
  return structuredClone(summary);
}
